title: "CMD — Cool Micro Designs"
description: "No bloated code. Just cool micro designs."
baseurl: "" # for GitHub Pages root repo
url: "https://hamuza11.github.io"
# With GitHub Pages Gem
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
navigation: navigation
force_theme: dark
theme_color: "#0d1117"
permalink: pretty

author:
  name: "Hamza"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
