title: "CMD — Cool Micro Designs"
description: "No bloated code. Just cool micro designs."
baseurl: "" # Leave blank unless you're using a custom subpath
url: "https://hamuza11.github.io" # Replace with your GitHub Pages URL

# Theme (clean & terminal-style)
theme: jekyll-theme-minimal

# GitHub Pages settings
markdown: kramdown
highlighter: rouge

# Author info (optional)
author:
  name: "Hamza"
  email: "hamuza11@outlook.com"

# Social links (optional)
social_links:
  youtube: https://youtube.com/@404CNFShorts
  github: https://github.com/Hamuza11

# Extra options
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these from build
exclude:
  - README.md
  - LICENSE
  - "*.psd"
