title: "Hamza's Spielstudio"
description: "Spiele & Apps für alle Plattformen. Schnell. Fair."
baseurl: "" # for GitHub Pages root repo
url: "https://hamuza11.github.io"
# With GitHub Pages Gem
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
navigation: navigation
force_theme: dark
theme_color: "#0d1117"
permalink: pretty

lang: de
locale: de_DE

author:
  name: "Hamza"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      lang: de
      layout: default
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      lang: de
 cursor/website-enhancement-with-german-translation-and-blog-a4a5
  - scope:
      path: "en"
    values:
      lang: en
      locale: en_US
      navigation: navigation_en


seo:
  title: "CMD — Coole Micro Designs"
  description: "Kein aufgeblähter Code. Nur coole Micro-Designs."
  locale: de_DE
